### ISSUE TITLE
db_libs.redis_lib 报错

### ISSUE THREAD

**Issue by User-Clb** [ydf0509/db_libs#2]
![屏幕截图 2023-10-27 225033](https://github.com/ydf0509/db_libs/assets/61401721/c9c67529-f4ab-4f09-b9a5-9b0a188ac0e6)

**Comment by ydf0509** [comment]
三方包版本问题

**Comment by ydf0509** [comment]
因为你MySQLdb 版本太高了你，三方包的人设计水平前瞻性有限，老是改代码。

db_libs 0.8版本__init__.py去掉了导入torndb_for_python3了，

**Comment by ydf0509** [comment]
因为你MySQLdb 版本太高了你，三方包的人设计水平前瞻性有限，老是改代码。

db_libs 0.8版本__init__.py去掉了导入torndb_for_python3了，

**Comment by User-Clb** [comment]
更新后没问题了
